# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idcate', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to=b'')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSlideshow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to=b'')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idproduct', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('price_sale', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('idcategory', models.ForeignKey(db_column='idcate', on_delete=django.db.models.deletion.CASCADE, related_name='cate', to='web.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SizePhoto',
            fields=[
                ('idsize', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('idslide', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='photoslideshow',
            name='idslideshow',
            field=models.ForeignKey(db_column='idslide', on_delete=django.db.models.deletion.CASCADE, related_name='slide', to='web.Slideshow'),
        ),
        migrations.AddField(
            model_name='photoslideshow',
            name='sizephoto',
            field=models.ForeignKey(db_column='idsize', on_delete=django.db.models.deletion.CASCADE, related_name='sizeslide', to='web.SizePhoto'),
        ),
        migrations.AddField(
            model_name='photoproduct',
            name='idproduct',
            field=models.ForeignKey(db_column='idproduct', on_delete=django.db.models.deletion.CASCADE, related_name='pro', to='web.Product'),
        ),
        migrations.AddField(
            model_name='photoproduct',
            name='sizephoto',
            field=models.ForeignKey(db_column='idsize', on_delete=django.db.models.deletion.CASCADE, related_name='sizepro', to='web.SizePhoto'),
        ),
    ]
