# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='photo/')),
                ('direct', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSlideshow',
            fields=[
                ('objectid', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('direct', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.FileField(upload_to='photo/')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('objectid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('price_sale', models.CharField(max_length=50)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('catgory', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, related_name='Wars', to='web.Category')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.PhotoProduct')),
            ],
        ),
    ]
