# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTest',
            fields=[
                ('objectid', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
